project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project: Airbnb Properties in Kauai, Hawaii"
  site-url: "https://musa-550-fall-2023.github.io/airbnb-properties-in-kauai" 
  repo-url: https://github.com/MUSA-550-Fall-2023/airbnb-properties-in-kauai
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Nick Hand and Alice Han, 2023"

  sidebar:
    logo: "images/kauai-flower.png"
    pinned: true
    align: center     

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - section: analysis/index.qmd
        contents:
          - analysis/final-project.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




